WRO-8014: [POC] Enact WebXR Components - Code cleanup
enactjs/sandstone pull request #1288
Opened 2022-07-20 12:53 UTC by vladut-clapou-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Code cleanup for Sandstone 3d components

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRO-8014

### Comments

2022-07-21 15:35 UTC, stanca-pop-lgp commented on ImageItem3D/ImageItem3D.js
> +import {get3DShape} from '../internal/util/util';
You can shorten this to: import {get3DShape} from '../internal/util';
I would also recommend to name this "utils", it is more common.

2022-07-21 15:50 UTC, stanca-pop-lgp commented on ImageItem3D/ImageItem3D.js
> +		setControlled: () => { }
You can leave it without the empty space between curly brakets.

2022-07-21 15:53 UTC, stanca-pop-lgp commented on ImageItem3D/ImageItem3D.js
> +
You can remove this empty line. (it's the same structure as for 'handlePointerDown' for example, and we don't have an empty line there - line 69)

2022-07-21 15:54 UTC, stanca-pop-lgp commented on ImageItem3D/ImageItem3D.js
Please remove one empty line.

2022-07-21 15:56 UTC, stanca-pop-lgp commented on samples/sampler/stories/default/Button3D.js
> +import  Button3D from '@enact/sandstone/Button3D';
Please remove the empty space before Button3D.

2022-07-21 15:57 UTC, stanca-pop-lgp requested changes
I left some comments. Thanks!

2022-07-22 10:50 UTC, stanca-pop-lgp approved these changes
LGTM

2022-07-25 08:16 UTC, alexandrumorariu commented on Button3D/Button3D.js
>  import sandstoneIcons from '../fonts/Sandstone_Icons.woff';
Order imports here

2022-07-25 10:22 UTC, alexandrumorariu approved these changes
LGTM

2022-07-25 10:22 UTC, merged