WRP-4952: TransferListPOC - Added support for VirtualGridList
enactjs/sandstone pull request #1370
Opened 2022-12-21 09:24 UTC by daniel-stoian-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
TransferList only supported VirtualList as component for source or destination list

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Added support for VirtualGridList. Now there is a prop that can choose which component to use to render the lists

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRP-4952

### Comments

Enact-DCO-1.0-Signed-off-by: Daniel Stoian [daniel.stoian@lgepartner.com](mailto:daniel.stoian@lgepartner.com)

2022-12-21 12:51 UTC, stanca-pop-lgp commented on TransferList/TransferList.js
> +				hd: svgGenerator(200, 200,  `${element}`),
I suggest not adding a text on the image as it repeats itself in the label.

2022-12-21 12:59 UTC, stanca-pop-lgp requested changes
Please check out my comments.

2022-12-21 12:59 UTC, stanca-pop-lgp commented on TransferList/TransferList.js
> +		 * The type of component used to render the list of items
Please add a dot at the end.

2022-12-21 12:59 UTC, stanca-pop-lgp commented on TransferList/TransferList.js
> +		 * @default sandstone/Icon.Icon
Please replace this with VirtualList.

2022-12-21 12:59 UTC, stanca-pop-lgp commented on TransferList/TransferList.js
> +			const selectionComponent = () => {
Please add some css so that checkmark is not glued to selection order number.

2022-12-21 12:59 UTC, stanca-pop-lgp commented on TransferList/TransferList.js
> +							verticalScrollbar="hidden"
Why did you add `verticalScrollbar="hidden"`? Same below.

2022-12-21 14:43 UTC, stanca-pop-lgp approved these changes
LGTM

2022-12-22 10:14 UTC, adrian-cocoara-lgp approved these changes
LGTM

2022-12-22 10:15 UTC, merged