WRP-567: Deprecate `value` prop to be replaced by `defaultValue` in `InputPopupBase`
enactjs/sandstone pull request #1377
Opened 2023-01-05 07:28 UTC by MikyungKim

### Checklist

* [ ] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [ ] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
`value` prop in `InputPopupBase` is used for the initial value but the name of the prop is somewhat confusing.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Deprecate `value` prop to be replaced by the newly added `defaultValue`. 

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)
The description of `value` in `Input` component is incorrect so I fixed it.
I've added documentation of `defaultValue` in `Input` component.

### Links
[//]: # (Related issues, references)
WRP-567

### Comments
Enact-DCO-1.0-Signed-off-by: Mikyung Kim (mikyung27.kim@lge.com)

2023-01-26 08:39 UTC, 0x64 requested changes

2023-01-26 08:39 UTC, 0x64 commented on CHANGELOG.md
> +- `sandstone/Input.InputPopupBase` prop `value`, to be removed in 3.0.0. Use `sandstone/Input.InputPopupBase` prop `defaultValue` instead.
```suggestion
- `sandstone/Input.InputPopupBase` prop `value`, to be removed in 3.0.0. Use `defaultValue` instead.
```

2023-01-26 08:39 UTC, 0x64 commented on CHANGELOG.md
> +- `sandstone/Input.InputPopupBase` prop `value`, to be removed in 3.0.0. Use `sandstone/Input.InputPopupBase` prop `defaultValue` instead.
I prefer a simpler one if clear enough. ;)

2023-01-26 08:39 UTC, 0x64 commented on Input/Input.js
> +					defaultValue={value}
Let's remove this line to prevent future misunderstanding.

2023-01-27 04:27 UTC, 0x64 commented on Input/Input.js
> +					defaultValue={value}
Closing after discussion: we need this.

2023-01-27 04:49 UTC, MikyungKim commented on CHANGELOG.md
> +- `sandstone/Input.InputPopupBase` prop `value`, to be removed in 3.0.0. Use `sandstone/Input.InputPopupBase` prop `defaultValue` instead.
✔️

2023-01-27 06:38 UTC, 0x64 approved these changes
💡

2023-01-31 01:41 UTC, seunghoh approved these changes

2023-01-31 01:41 UTC, merged