added helpful comments
enactjs/sandstone pull request #1450
Opened 2023-05-18 10:53 UTC by adrian-cocoara-lgp

Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Added helpful comments through the code

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRP-15613

### Comments

2023-05-22 15:02 UTC, daniel-stoian-lgp commented on TransferList/TransferList.js
> +			// Called when an item from the list is selected with name, index and parent list (ex: BBC World News 0 first)
```suggestion
			// Called when an item from the list is selected. The information contains the name, index and parent list (ex: BBC World News 0 first)
```

2023-05-22 15:05 UTC, daniel-stoian-lgp commented
Please also try to add comments to actions happening inside the functions.
I'm just pointing an example but there are many others: 

![image](https://github.com/enactjs/sandstone/assets/63335068/8b12b7c9-fb2e-4e6c-9ab8-f03d74ea7716)

2023-05-26 07:21 UTC, daniel-stoian-lgp approved these changes

2023-05-26 10:04 UTC, stanca-pop-lgp requested changes

2023-05-26 10:04 UTC, stanca-pop-lgp commented on TransferList/TransferList.js
> +		// Restricts the spotlight only to the component
```suggestion
		// Restrict the spotlight only to the component
```

2023-05-26 12:04 UTC, stanca-pop-lgp approved these changes

2023-05-26 12:04 UTC, merged