WRP-17258: Fix `scroller/EditableWrapper` to release selectedItem when focus leaves scroll container
enactjs/sandstone pull request #1460
Opened 2023-06-15 05:32 UTC by juwonjeong

Enact-DCO-1.0-Signed-off-by: Juwon Jeong (juwon.jeong@lge.com)

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [ ] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)

In this PR, I fixed 2 issues related to `scroller/EditableWrapper`

1) Fix `scroller/EditableWrapper` to release selectedItem when focus leaves the scroll container.
: When an item is selected in the editable scroller and the focus leaves the scroll container(e.g., by key handling), the selected item remains selected even if the focus moves back into the scroll container. 
 -> It is fixed to release selectedItem when the focus leaves the scroll container. 

2) Fix `scroller/EditableWrapper` centeredOffset to calculate properly.
: When deleting an item after scrolling, centeredOffset was miscalculated. 

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

1) In the handleKeyDownCapture handler, when keyCode is 'up' or 'down', find the next spotlight item and if it is not included in the scroll container, release selectedItem and reset.

2) When deleting an item after scrolling, it needs to consider the container.scrollLeft too as getBoundingClientRect only considers the relative left position of the viewport.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRP-17258

### Comments

2023-06-20 09:25 UTC, 0x64 approved these changes

2023-06-21 10:04 UTC, seunghoh requested changes
Edit mode > item move, hide > enter to finish edit > scroll to the final items > press up key to focus the edit button 
but focus doesn't move

2023-06-22 04:35 UTC, juwonjeong commented
> Edit mode > item move, hide > enter to finish edit > scroll to the final items > press up key to focus the edit button but focus doesn't move

I fixed the above focus handling issue.

2023-06-22 23:57 UTC, seunghoh approved these changes
LGTM

2023-06-22 23:57 UTC, merged