PLAT-111125: ImageItem resizing issues
enactjs/sandstone pull request #857
Opened 2021-03-23 15:09 UTC by stanca-pop-lgp

Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [x] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [x] At least one test case is included for this feature or bug fix
* [x] Documentation was added or is not needed
* [ ] This is an API breaking change

### Resolution
Fixed ImageItem resizing issues. Added scaling to parent div in sampler and imported Image instead of ImageBase for the imageComponent prop, as Image component is wrapped in the ResponsiveImageDecorator which fixes the problem concerning the updating of the image to reflect the new sizing.

### Links
PLAT-111125

### Comments

2021-03-24 07:31 UTC, daniel-stoian-lgp approved these changes

2021-03-24 10:56 UTC, adrian-cocoara-lgp approved these changes

2021-04-08 08:35 UTC, MikyungKim commented on samples/sampler/stories/default/ImageItem.js
> +	<div style={{width: ri.scaleToRem(800), height: ri.scaleToRem(600)}}>
Let's not add this div.

2021-04-08 08:48 UTC, MikyungKim commented on samples/sampler/stories/default/ImageItem.js
> -			width: ri.scale(select('orientation', prop.orientation, Config) === 'vertical' ? 768 : 1020),
Please just change the `ri.scale` to `ri.scaleToRem` in this sampler.

2021-04-08 08:49 UTC, MikyungKim requested changes
Please merge develop and put the change log at the right place :)

2021-04-12 04:52 UTC, MikyungKim approved these changes
LGTM

2021-04-12 05:00 UTC, merged